### ISSUE TITLE
Roundcube auto login without cookies

### ISSUE THREAD

**Issue by DimGujjar** [alexjeen/Roundcube-AutoLogin#3]
Currently I can login to Roundcube email client from my custom login form. The login details that I enter in my form are not same as the login details used for login to Roundcube. There is an intermediate process that translates entered login details  into real Roundcube login details. I used Roundcube auto login [class.](https://github.com/alexjeen/Roundcube-AutoLogin)

It works fine But its a login by setting the cookies and then redirecting to Roundcube.
When I save password in my browser instead of saving the login details entered in the form the internal login details are saved and are populated in the form on later login. I want to send the login and password to Roundcube and login and not set the cookies.

**Comment by alexjeen** [comment]
The cookies are not set on the client device, they are set in the class itself (in the cookiejar.txt file). If you don't set these cookies on the client using a function like cookie() there will be no cookies set.

So can't you just ignore the return value?
